/* GearShare — app.js */
'use strict';
const state={currentPage:'home',authMode:'login',user:null,equipment:[{id:1,name:'Oscilloscope DS1054Z',category:'Electronics',price:8,unit:'day',rating:4.9,reviews:23,icon:'📡',desc:'4-channel digital oscilloscope. 50MHz bandwidth, perfect for circuit analysis.',owner:'Arjun K.',available:true,condition:'Excellent'},{id:2,name:'3D Printer Ender 3',category:'Fabrication',price:15,unit:'day',rating:4.7,reviews:17,icon:'🖨️',desc:'FDM 3D printer, 220x220x250mm build volume. Includes PLA filament sample.',owner:'Priya M.',available:true,condition:'Good'},{id:3,name:'Soldering Station',category:'Electronics',price:3,unit:'day',rating:4.8,reviews:41,icon:'🔧',desc:'Temperature-controlled station, 60W. Perfect for PCB work.',owner:'Ravi S.',available:true,condition:'Excellent'},{id:4,name:'Multimeter Fluke 87V',category:'Electronics',price:5,unit:'day',rating:5.0,reviews:8,icon:'🔌',desc:'Industrial grade True-RMS multimeter with temperature measurement.',owner:'Ananya T.',available:true,condition:'Like New'},{id:5,name:'Laser Cutter Access',category:'Fabrication',price:20,unit:'session',rating:4.6,reviews:12,icon:'⚡',desc:'CO2 laser cutter, A3 bed. Cuts acrylic, wood, leather up to 8mm.',owner:'Kiran P.',available:false,condition:'Good'},{id:6,name:'Arduino Mega Kit',category:'Microcontrollers',price:2,unit:'day',rating:4.9,reviews:55,icon:'🤖',desc:'Full kit with 100+ components: sensors, motors, displays, breadboard.',owner:'Sneha R.',available:true,condition:'Good'}],filters:{category:[],maxPrice:50},selectedEquip:null,conditionSelected:'Like New'};
const $$=(s,c=document)=>[...c.querySelectorAll(s)];
function showPage(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));const el=document.getElementById('page-'+p);if(el){el.classList.add('active');state.currentPage=p;}$$('.nav-links a').forEach(a=>a.classList.toggle('active',a.dataset.page===p));window.scrollTo({top:0,behavior:'smooth'});if(p==='listing')renderListing();}
function setAuthMode(m){state.authMode=m;$$('.auth-tab').forEach(t=>t.classList.toggle('active',t.dataset.mode===m));const lf=document.getElementById('login-form'),rf=document.getElementById('register-form');if(lf)lf.style.display=m==='login'?'block':'none';if(rf)rf.style.display=m==='register'?'block':'none';}
function showToast(msg,type='info',dur=3000){const icons={success:'✅',error:'❌',info:'ℹ️'};const c=document.getElementById('toast-container');if(!c)return;const el=document.createElement('div');el.className='toast '+type;el.innerHTML='<span class="toast-icon">'+icons[type]+'</span><span class="toast-msg">'+msg+'</span>';c.appendChild(el);setTimeout(()=>{el.style.animation='slideOut .3s ease forwards';setTimeout(()=>el.remove(),300);},dur);}
function equipCard(e){const unavail=!e.available?'<div style="position:absolute;inset:0;background:rgba(13,17,23,.65);display:flex;align-items:center;justify-content:center;z-index:2;font-size:.82rem;font-weight:700;color:#e74c3c;letter-spacing:.08em">UNAVAILABLE</div>':'';const btn=e.available?'<button class="btn btn-primary btn-sm rent-btn" data-id="'+e.id+'">Rent Now</button>':'<button class="btn btn-sm" data-id="'+e.id+'" style="opacity:.4;cursor:not-allowed;background:var(--dark3);color:var(--muted);border-radius:99px;padding:8px 18px;font-size:.85rem" disabled>Unavailable</button>';return'<div class="equip-card" data-id="'+e.id+'"><div class="equip-img"><span style="position:relative;z-index:1;font-size:3.5rem">'+e.icon+'</span><div class="equip-img-overlay"></div><div class="equip-badge"><span class="badge">'+e.condition+'</span></div>'+unavail+'</div><div class="equip-body"><div class="equip-meta"><span class="equip-category">'+e.category+'</span><span class="equip-rating"><span class="stars">★</span> '+e.rating+' ('+e.reviews+')</span></div><div class="equip-name">'+e.name+'</div><div class="equip-desc">'+e.desc+'</div><div class="equip-footer"><div class="equip-price">₹'+e.price+' <small>/ '+e.unit+'</small></div>'+btn+'</div><div class="equip-user" style="margin-top:10px;padding-top:10px;border-top:1px solid var(--border)"><div class="user-av">'+e.owner[0]+'</div>'+e.owner+'</div></div></div>';}
function attachCardEvents(grid){grid.querySelectorAll('.rent-btn').forEach(b=>b.addEventListener('click',function(ev){ev.stopPropagation();openBookingModal(parseInt(this.dataset.id));}));grid.querySelectorAll('.equip-card').forEach(c=>c.addEventListener('click',function(){openBookingModal(parseInt(this.dataset.id));}));}
function renderListing(){const grid=document.getElementById('results-grid');if(!grid)return;const sv=(document.getElementById('search-input')||{}).value||'';const f=state.equipment.filter(e=>{const catOk=state.filters.category.length===0||state.filters.category.includes(e.category);const priceOk=e.price<=state.filters.maxPrice;const sOk=!sv||e.name.toLowerCase().includes(sv.toLowerCase())||e.category.toLowerCase().includes(sv.toLowerCase())||e.desc.toLowerCase().includes(sv.toLowerCase());return catOk&&priceOk&&sOk;});const cnt=document.getElementById('results-count');if(cnt)cnt.innerHTML='Showing <strong>'+f.length+'</strong> items';grid.innerHTML=f.map(e=>equipCard(e)).join('');attachCardEvents(grid);}
function renderFeaturedHome(){const grid=document.getElementById('home-equipment-grid');if(!grid)return;grid.innerHTML=state.equipment.slice(0,3).map(e=>equipCard(e)).join('');attachCardEvents(grid);}
function openBookingModal(id){const equip=state.equipment.find(e=>e.id===id);if(!equip||!equip.available)return;state.selectedEquip=equip;const modal=document.getElementById('booking-modal');if(!modal)return;document.getElementById('modal-equip-icon').textContent=equip.icon;document.getElementById('modal-equip-name').textContent=equip.name;document.getElementById('modal-equip-cat').textContent=equip.category+' · '+equip.condition;updateModalPrice();modal.classList.add('open');document.body.style.overflow='hidden';}
function closeBookingModal(){const m=document.getElementById('booking-modal');if(m)m.classList.remove('open');document.body.style.overflow='';}
function updateModalPrice(){const eq=state.selectedEquip;if(!eq)return;const d=document.getElementById('rental-days');const days=d?(parseInt(d.value)||1):1;const t=eq.price*days;const pe=document.getElementById('modal-price');if(pe)pe.textContent='₹'+t;const be=document.getElementById('modal-price-breakdown');if(be)be.textContent='₹'+eq.price+'/'+eq.unit+' × '+days+' day'+(days>1?'s':'');}
function initFilters(){$$('.filter-cat').forEach(cb=>cb.addEventListener('change',()=>{state.filters.category=$$('.filter-cat:checked').map(c=>c.value);renderListing();}));const r=document.getElementById('price-range');if(r)r.addEventListener('input',()=>{state.filters.maxPrice=parseInt(r.value);const d=document.getElementById('price-display');if(d)d.textContent='₹'+r.value;renderListing();});}
function initUpload(){const dz=document.getElementById('dropzone');if(!dz)return;dz.addEventListener('dragover',e=>{e.preventDefault();dz.classList.add('dragover');});dz.addEventListener('dragleave',()=>dz.classList.remove('dragover'));dz.addEventListener('drop',e=>{e.preventDefault();dz.classList.remove('dragover');handleFiles(e.dataTransfer.files);});const fi=document.getElementById('file-input');if(fi)fi.addEventListener('change',()=>handleFiles(fi.files));$$('.condition-pill').forEach(p=>p.addEventListener('click',()=>{$$('.condition-pill').forEach(x=>x.classList.remove('active'));p.classList.add('active');state.conditionSelected=p.dataset.val;}));$$('.avail-btn').forEach(b=>b.addEventListener('click',()=>b.classList.toggle('active')));const ni=document.getElementById('upload-name'),pi=document.getElementById('upload-price'),di=document.getElementById('upload-desc');if(ni)ni.addEventListener('input',()=>{const e=document.getElementById('preview-name');if(e)e.textContent=ni.value||'Equipment Name';});if(pi)pi.addEventListener('input',()=>{const e=document.getElementById('preview-price');if(e)e.textContent=pi.value?'₹'+pi.value:'₹0';});if(di)di.addEventListener('input',()=>{const e=document.getElementById('preview-desc');if(e)e.textContent=di.value||'Your description will appear here...';});}
function handleFiles(files){const p=document.getElementById('dropzone-preview');if(!p)return;p.innerHTML='';const em=['🔧','📡','🖨️','🔌','⚡'];Array.from(files).slice(0,5).forEach((f,i)=>{const el=document.createElement('div');el.className='preview-thumb';el.textContent=em[i%em.length];p.appendChild(el);});const ic=document.getElementById('preview-icon');if(ic)ic.textContent=em[0];showToast(Math.min(files.length,5)+' image(s) ready','success');}
function animateCounters(){$$('.stat-num[data-target]').forEach(el=>{const t=parseInt(el.dataset.target),s=el.dataset.suffix||'';let c=0;const step=Math.ceil(t/60);const timer=setInterval(()=>{c=Math.min(c+step,t);el.textContent=c+s;if(c>=t)clearInterval(timer);},25);});}
document.addEventListener('DOMContentLoaded',()=>{
  $$('.nav-links a[data-page]').forEach(a=>a.addEventListener('click',()=>showPage(a.dataset.page)));
  const logo=document.querySelector('.nav-logo');if(logo)logo.addEventListener('click',()=>showPage('home'));
  document.querySelectorAll('[data-goto]').forEach(el=>el.addEventListener('click',function(){const p=this.dataset.goto;if(p==='auth'&&this.textContent.includes('Sign Up'))setAuthMode('register');showPage(p);}));
  $$('.auth-tab').forEach(t=>t.addEventListener('click',()=>setAuthMode(t.dataset.mode)));
  const lrl=document.getElementById('login-reg-link');if(lrl)lrl.addEventListener('click',e=>{e.preventDefault();setAuthMode('register');});
  const rll=document.getElementById('reg-login-link');if(rll)rll.addEventListener('click',e=>{e.preventDefault();setAuthMode('login');});
  const lfe=document.getElementById('login-form-el');if(lfe)lfe.addEventListener('submit',e=>{e.preventDefault();const em=(document.getElementById('login-email')||{}).value||'';const pw=(document.getElementById('login-pass')||{}).value||'';if(!em||!em.includes('@')){showToast('Please enter a valid email','error');return;}if(pw.length<6){showToast('Password min 6 characters','error');return;}const btn=document.getElementById('login-btn');if(btn){btn.textContent='Signing in...';btn.disabled=true;}setTimeout(()=>{state.user={email:em,name:'Student User'};showToast('Welcome back! 🎉','success');showPage('home');if(btn){btn.textContent='Sign In';btn.disabled=false;}},1200);});
  const rfe=document.getElementById('register-form-el');if(rfe)rfe.addEventListener('submit',e=>{e.preventDefault();const n=(document.getElementById('reg-name')||{}).value||'';const em=(document.getElementById('reg-email')||{}).value||'';const pw=(document.getElementById('reg-pass')||{}).value||'';const cf=(document.getElementById('reg-confirm')||{}).value||'';const tr=(document.getElementById('reg-terms')||{}).checked;if(!n){showToast('Enter your full name','error');return;}if(!em||!em.includes('@')){showToast('Valid email required','error');return;}if(pw.length<8){showToast('Password min 8 chars','error');return;}if(pw!==cf){showToast('Passwords do not match','error');return;}if(!tr){showToast('Accept Terms of Service','error');return;}const btn=document.getElementById('register-btn');if(btn){btn.textContent='Creating...';btn.disabled=true;}setTimeout(()=>{state.user={name:n,email:em};showToast('Account created! 🚀','success');showPage('home');if(btn){btn.textContent='Create Account';btn.disabled=false;}},1400);});
  const ufe=document.getElementById('upload-form-el');if(ufe)ufe.addEventListener('submit',e=>{e.preventDefault();const nm=(document.getElementById('upload-name')||{}).value||'';const pr=(document.getElementById('upload-price')||{}).value||'';const ct=(document.getElementById('upload-category')||{}).value||'';const ds=(document.getElementById('upload-desc')||{}).value||'';if(!nm||!pr||!ct||!ds){showToast('Fill in all required fields','error');return;}const btn=document.getElementById('upload-submit-btn');if(btn){btn.textContent='⏳ Publishing...';btn.disabled=true;}setTimeout(()=>{state.equipment.unshift({id:Date.now(),name:nm,category:ct,price:parseInt(pr),unit:'day',rating:5.0,reviews:0,icon:'🔧',desc:ds,owner:(state.user&&state.user.name)||'You',available:true,condition:state.conditionSelected||'Good'});showToast('"'+nm+'" listed! ✅','success');if(btn){btn.textContent='🚀 Publish Listing';btn.disabled=false;}showPage('listing');},1600);});
  const modal=document.getElementById('booking-modal');if(modal)modal.addEventListener('click',e=>{if(e.target===modal)closeBookingModal();});
  const mc=document.getElementById('modal-close-btn');if(mc)mc.addEventListener('click',closeBookingModal);
  const cb=document.getElementById('confirm-booking-btn');if(cb)cb.addEventListener('click',()=>{const eq=state.selectedEquip;if(!eq)return;const de=document.getElementById('rental-days');const days=de?(parseInt(de.value)||1):1;cb.textContent='Processing...';cb.disabled=true;setTimeout(()=>{closeBookingModal();showToast('Booking confirmed! 🎉','success');cb.textContent='💳 Confirm & Pay';cb.disabled=false;},1500);});
  const de=document.getElementById('rental-days');if(de)de.addEventListener('input',updateModalPrice);
  $$('.payment-option').forEach(o=>o.addEventListener('click',()=>{$$('.payment-option').forEach(x=>x.classList.remove('active'));o.classList.add('active');}));
  const si=document.getElementById('search-input');if(si){let t;si.addEventListener('input',()=>{clearTimeout(t);t=setTimeout(renderListing,300);});}
  const sb=document.getElementById('search-btn');if(sb)sb.addEventListener('click',renderListing);
  $$('[data-toggle-pass]').forEach(b=>b.addEventListener('click',()=>{const el=document.getElementById(b.dataset.togglePass);if(!el)return;const ip=el.type==='password';el.type=ip?'text':'password';b.textContent=ip?'🙈':'👁';}));
  initFilters();initUpload();showPage('home');setTimeout(animateCounters,500);renderFeaturedHome();
});
